package main

import (
	"net/http"
	"path/filepath"
	"sync"
	"time"

	"github.com/xuri/excelize/v2"
)

var recordsMu sync.Mutex

func sheetWithHeaders(f *excelize.File, name string, headers []string) {
	idx, _ := f.GetSheetIndex(name)
	if idx == -1 {
		f.NewSheet(name)
	}
	row := make([]any, len(headers))
	for i, h := range headers {
		row[i] = h
	}
	f.SetSheetRow(name, "A1", &row)
	style, _ := f.NewStyle(&excelize.Style{Font: &excelize.Font{Bold: true}})
	end, _ := excelize.CoordinatesToCellName(len(headers), 1)
	f.SetCellStyle(name, "A1", end, style)
	f.SetPanes(name, &excelize.Panes{Freeze: true, YSplit: 1, TopLeftCell: "A2", ActivePane: "bottomLeft"})
}

func appendRow(f *excelize.File, sheet string, rowNo int, vals []any) {
	cell, _ := excelize.CoordinatesToCellName(1, rowNo)
	f.SetSheetRow(sheet, cell, &vals)
}

var caseExportHeaders = []string{"Case", "Title", "Type", "Status", "Owner", "Covered by", "Next action due",
	"Hard deadline", "Waiting on", "Waiting detail", "Waiting since", "Source", "Location", "Tags",
	"Description", "Created", "Last updated", "Completed", "Recurring"}

func (s *server) fillCasesSheet(f *excelize.File, sheet string) error {
	sheetWithHeaders(f, sheet, caseExportHeaders)
	rows, err := s.db.Query(caseSelect + ` ORDER BY c.case_no`)
	if err != nil {
		return err
	}
	defer rows.Close()
	n := 2
	for rows.Next() {
		c, err := scanCase(rows)
		if err != nil {
			continue
		}
		rec := ""
		if c.ObligationID != 0 {
			rec = "yes"
		}
		appendRow(f, sheet, n, []any{c.CaseNo, c.Title, c.TypeName, c.Status, c.OwnerName, c.CovererName,
			c.DueDate, c.Deadline, c.WaitingOn, c.WaitingDetail, c.WaitingSince, c.Source, c.Location, c.Tags,
			c.Description, c.CreatedAt, c.UpdatedAt, c.CompletedAt, rec})
		n++
	}
	return nil
}

func (s *server) fillActivitySheet(f *excelize.File, sheet, from, to string) error {
	sheetWithHeaders(f, sheet, []string{"At", "Case", "Actor", "Kind", "Detail"})
	q := `SELECT e.at,c.case_no,COALESCE(m.name,'System'),e.kind,e.payload FROM events e
JOIN cases c ON c.id=e.case_id LEFT JOIN members m ON m.id=e.actor_id WHERE 1=1`
	args := []any{}
	if from != "" {
		q += ` AND e.at>=?`
		args = append(args, from)
	}
	if to != "" {
		q += ` AND e.at<=?`
		args = append(args, to+"T23:59:59Z")
	}
	q += ` ORDER BY e.id`
	rows, err := s.db.Query(q, args...)
	if err != nil {
		return err
	}
	defer rows.Close()
	n := 2
	for rows.Next() {
		var at, caseNo, actor, kind, payload string
		if rows.Scan(&at, &caseNo, &actor, &kind, &payload) == nil {
			appendRow(f, sheet, n, []any{at, caseNo, actor, kind, payload})
			n++
		}
	}
	return nil
}

func (s *server) buildExaminerWorkbook(from, to, generatedBy string) (*excelize.File, error) {
	f := excelize.NewFile()
	f.SetSheetName("Sheet1", "Summary")
	team := getMeta(s.db, "team_name")
	rangeText := "all history"
	if from != "" || to != "" {
		rangeText = from + " to " + to
	}
	lines := [][]any{
		{"Casebook examiner package"},
		{"Team", team},
		{"Generated at", time.Now().Format("2006-01-02 15:04:05 MST")},
		{"Generated by", generatedBy},
		{"Activity range", rangeText},
		{"Note", "Cases and checklists reflect current state; the Activity sheet is the append-only audit log."},
	}
	for i, l := range lines {
		appendRow(f, "Summary", i+1, l)
	}
	if err := s.fillCasesSheet(f, "Cases"); err != nil {
		return nil, err
	}
	if err := s.fillActivitySheet(f, "Activity", from, to); err != nil {
		return nil, err
	}
	sheetWithHeaders(f, "Checklists", []string{"Case", "Item", "State"})
	rows, err := s.db.Query(`SELECT c.case_no,ci.label,ci.state FROM checklist_items ci JOIN cases c ON c.id=ci.case_id ORDER BY c.case_no,ci.sort`)
	if err == nil {
		n := 2
		for rows.Next() {
			var caseNo, label, state string
			if rows.Scan(&caseNo, &label, &state) == nil {
				appendRow(f, "Checklists", n, []any{caseNo, label, state})
				n++
			}
		}
		rows.Close()
	}
	sheetWithHeaders(f, "Recurring", []string{"Name", "Type", "Repeats", "Next due", "Lead days", "Default owner", "Active", "Checklist template"})
	n := 2
	for _, o := range s.listObligations() {
		active := "yes"
		if !o.Active {
			active = "paused"
		}
		tpl := ""
		for i, it := range o.Checklist {
			if i > 0 {
				tpl += "; "
			}
			tpl += it
		}
		appendRow(f, "Recurring", n, []any{o.Name, o.TypeName, o.Frequency, o.NextDue, o.LeadDays, o.OwnerName, active, tpl})
		n++
	}
	sheetWithHeaders(f, "Members", []string{"Name", "Active", "Workspace admin"})
	n = 2
	for _, m := range s.listMembers() {
		active, admin := "yes", ""
		if !m.Active {
			active = "no"
		}
		if m.IsAdmin {
			admin = "yes"
		}
		appendRow(f, "Members", n, []any{m.Name, active, admin})
		n++
	}
	return f, nil
}

func (s *server) handleExaminerExport(w http.ResponseWriter, r *http.Request) {
	actor, err := s.actor(r)
	if err != nil {
		writeErr(w, 401, err.Error())
		return
	}
	q := r.URL.Query()
	f, err := s.buildExaminerWorkbook(q.Get("from"), q.Get("to"), actor.Name)
	if err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	name := "examiner_package_" + time.Now().Format("20060102_150405") + ".xlsx"
	w.Header().Set("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
	w.Header().Set("Content-Disposition", `attachment; filename="`+name+`"`)
	f.Write(w)
}

// writeRecords refreshes the human-readable xlsx snapshots in Records/.
func writeRecords(s *server) error {
	recordsMu.Lock()
	defer recordsMu.Unlock()
	month := time.Now().Format("2006-01")
	fc := excelize.NewFile()
	fc.SetSheetName("Sheet1", "Cases")
	if err := s.fillCasesSheet(fc, "Cases"); err != nil {
		return err
	}
	if err := fc.SaveAs(filepath.Join(s.ws, "Records", "Cases_"+month+".xlsx")); err != nil {
		return err
	}
	fa := excelize.NewFile()
	fa.SetSheetName("Sheet1", "Activity")
	if err := s.fillActivitySheet(fa, "Activity", "", ""); err != nil {
		return err
	}
	return fa.SaveAs(filepath.Join(s.ws, "Records", "ActivityLog_"+month+".xlsx"))
}

func (s *server) handleRecordsRefresh(w http.ResponseWriter, r *http.Request) {
	if _, err := s.actor(r); err != nil {
		writeErr(w, 401, err.Error())
		return
	}
	if err := writeRecords(s); err != nil {
		writeErr(w, 500, err.Error())
		return
	}
	writeJSON(w, 200, map[string]any{"ok": true, "folder": filepath.Join(s.ws, "Records")})
}
